apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-restore-action-config
  labels:
    velero.io/plugin-config: ""
    velero.io/restic: RestoreItemAction
data:
  image: registry.cn-hangzhou.aliyuncs.com/acs/velero-restic-restore-helper:latest
  cpuRequest: 200m
  memRequest: 128Mi
  cpuLimit: 200m
  memLimit: 128Mi